### ISSUE TITLE
Replace references to OEFs in the extension field with something more accurate

### ISSUE THREAD

**Issue by unzvfu** [Plonky3/Plonky3#101]
The extension field code introduced in #95 refers to extensions defined by binomial irreducible polynomials as Optimal Extension Fields (OEFs) (e.g. `QuadraticOef`, `CubicOef`, `OptimallyExtendable` etc.). This naming was inherited from Plonky2, however it is not really accurate and could cause confusion. Moreover, depending on a particular architecture, we may want to consider implementations of field extensions with irreducible polynomials that are not binomial.

We should try to find more accurate names for the current traits and structs, and have a system of names that will not clash with choosing irreducible polynomials of other forms in the future.

**Comment by LKY-stephen** [comment]
Currently, the proposal that captures the main idea might be:
`OptimallyExtendable` ->`BinomialExtendable`
`XXXOef` -> `XXXBinomialExtensionField` (Or `XXXBEF` in short)
is this name acceptable? or any other suggestions?
