### ISSUE TITLE
`BabyBear` Extension Fields

### ISSUE THREAD

**Issue by LKY-stephen** [Plonky3/Plonky3#113]
For BabyBear, we need an extension instance for QuinticExtension (154-bit sec) or TesseracticExtension (123-bit sec).
In this higher degree, the frobenuis algorithm becomes explicitly faster for the inverse. if we only use this extension for the prime field (i.e., we force the base field to be the prime field and the extension field to be a generalized OEF), then we can embed the frobenuis algorithm inside these particular extension field structs.

The quintic binomial poly can be x^5-2, the generator is i+8
The Tesseract binomial poly can be x^4-11, and the generator is also i+8

**Comment by LKY-stephen** [comment]
Wait, we don't need extension field for babybear? I think the mentioned pr is just for quicker inverse of base field?

**Comment by dlubarov** [comment]
@LKY-stephen whoops yeah looks like it was accidentally linked that PR. Agreed this should be open.
