### ISSUE TITLE
Create benchmark for extension field

### ISSUE THREAD

**Issue by LKY-stephen** [Plonky3/Plonky3#130]

**Comment by LKY-stephen** [comment]
| Field | Square(ns) | Inv(ns) | Mul(ns) |
|--------|--------|--------|--------|
| `BinomialExtensionField<BabyBear, 4>`| 15.879| 152.17| 15.660|
| BinomialExtensionField<BabyBear, 5>| 24.375| 204.92| 24.498|
| `BinomialExtensionField<Goldilocks, 2>`| 9.3334| 177.79| 9.5519|
| `QuadraticBef<Goldilocks>`| 6.1542| 147.14| 7.4340|
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 2>`| 29.572| 122.02| 30.772| 
| `QuadraticBef<Mersenne31Complex<Mersenne31>>`| 22.785| 72.547| 26.657|
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 3>`| 70.264| 295.85| 73.039|
| `CubicBef<Mersenne31Complex<Mersenne31>>`| 42.416| 134.82| 62.071|

**Comment by LKY-stephen** [comment]
As https://github.com/Plonky3/Plonky3/pull/151#issuecomment-1752197239 suggested, we can optimize the result by adding to cargo.toml 
```
[profile.release]
lto = "fat"
codegen-units = 1
```

| Field | Square(ns) | Inv(ns) | Mul(ns) |
|--------|--------|--------|--------|
| `BinomialExtensionField<BabyBear, 4>`| 14.094| 158.38| 13.978|
| `BinomialExtensionField<BabyBear, 5>`| 21.609| 215.81| 22.232|
| `BinomialExtensionField<Goldilocks, 2>`| 1.5406| 140.62| 1.6737|
| `QuadraticBef<Goldilocks>`| 1.3471| 136.75| 1.546|
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 2>`| 8.2529| 75.858| 8.1932|
| `QuadraticBef<Mersenne31Complex<Mersenne31>>` |0.25872| 51.492| 0.257| 
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 3>`| 20.895| 119.47| 20.883|
| `CubicBef<Mersenne31Complex<Mersenne31>>`| 0.38587| 58.28| 0.38696|

**Comment by dlubarov** [comment]
Thanks for updating, I think something seems funny with `Mersenne31Complex<Mersenne31>`. The times you got for its `QuadraticBef` and `CubicBef` would be roughly a single cycle on most CPUs; seems too good to be true.

On my M1 I'm getting more expected times, like

(default config)
```
BinomialExtensionField<Mersenne31Complex<Mersenne31>, 3> mul
                        time:   [59.334 ns 59.379 ns 59.433 ns]
CubicBef<Mersenne31Complex<Mersenne31>> mul
                        time:   [50.086 ns 50.157 ns 50.246 ns]
```
(`lto = "fat"`, `codegen-units = 1`)
```
BinomialExtensionField<Mersenne31Complex<Mersenne31>, 3> mul
                        time:   [60.561 ns 60.832 ns 61.162 ns]
CubicBef<Mersenne31Complex<Mersenne31>> mul
                        time:   [50.965 ns 51.154 ns 51.382 ns]
```

**Comment by dlubarov** [comment]
Oh my mistake, I hadn't actually changed the config, after doing so I also see those extremely fast times. Will look into it.

**Comment by dlubarov** [comment]
Looks like we need to `black_box` the inputs, or use `bench_with_input` which does that for us; then the times with `lto = fat` look realistic.

**Comment by LKY-stephen** [comment]
After further adding black_box func the final benchmark are as following:

| Field | Square(ns) | Inv(ns) | Mul(ns) |
|--------|--------|--------|--------|
| `BinomialExtensionField<BabyBear, 4>`| 15.014| 160.74| 15.980|
| `BinomialExtensionField<BabyBear, 5>`| 22.061| 215.68| 22.121|
| `BinomialExtensionField<Goldilocks, 2>`| 2.6672| 142.72| 2.8484|
| `QuadraticBef<Goldilocks>`| 2.2181| 139.48| 2.7713|
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 2>`| 9.1203| 78.040| 9.96|
| `QuadraticBef<Mersenne31Complex<Mersenne31>>` |6.3807| 60.707| 9.6052| 
| `BinomialExtensionField<Mersenne31Complex<Mersenne31>, 3>`| 29.893| 129.17| 30.799|
| `CubicBef<Mersenne31Complex<Mersenne31>>`| 11.749| 75.907| 17.760| 

quadratic provide a 20~30% gain for Mersenne complex and cubic provide a 40~50% gain

**Comment by LKY-stephen** [comment]
@dlubarov @unzvfu, there is one last thing we need to decide. Should we keep the qudraticBef and cubicBef for mersenne31Complex?

**Comment by unzvfu** [comment]
> @dlubarov @unzvfu, there is one last thing we need to decide. Should we keep the qudraticBef and cubicBef for mersenne31Complex?

Personally I vote to remove them. I think if we ever need a faster implementation of an extension of `Mersenne31Complex`, then it would make more sense to implement that special case directly, rather than using `QuadraticBef` or `CubicBef`.

**Comment by dlubarov** [comment]
I'd vote to remove also. I think if we experiment with tweaks to `BinomialExtensionField` we can probably get the compiler to generate the same code for both; e.g. we could rewrite it to avoid `0 + something`, or worst case we could write `match D { ... }` in a few places.
