### ISSUE TITLE
Poseidon2: use specialized matrix for external rounds

### ISSUE THREAD

**Issue by dlubarov** [Plonky3/Plonky3#134]
I think we initially misunderstood Poseidon2 as requiring an MDS matrix for external (a.k.a. full) rounds. After looking at it more carefully, it seems the (external) linear layer they propose is not MDS (although it uses a 4x4 MDS matrix as a building block), but has a slightly weaker diffusion property. It seems like it should probably be faster than any MDS layer.

cc @jtguibas @vivekvpandya

**Comment by jorgeantonio21** [comment]
I would like to understand this issue more in detail and possibly tackle it. Will take a look at the original paper, in the meantime.

**Comment by jtguibas** [comment]
Thanks for flagging @dlubarov. I think I missed this detail during my initial implementation.

We should probably change the external round to not use the `Mds` trait and instead have another trait inside the `poseidon2` crate to reflect this.
