### ISSUE TITLE
the compression and decompression logic

### ISSUE THREAD

**Issue by LKY-stephen** [Plonky3/Plonky3#159]

**Comment by LKY-stephen** [comment]
Just to confirm if my understanding is correct.  Currently, `Mersenne31Dft` supports interpolating a Mersenne31 poly into a Mersenne31Complex. 

This ticket will further compress the Mersenne31Complex poly to a Mersenn31 Poly and two Mersenne31Complex parameter($\tau;c_0$).

So we will provide a new structure for storing the matrix and a vector of $\tau;c_0$ to replace current 
 RowMajorMatrix<Ext>?

**Comment by LKY-stephen** [comment]
After double-checking the code and some experiments, I think the existing DFT (`Mersenne31Dft`) has already compressed the interpolation somehow, and https://eprint.iacr.org/2023/824 seems cannot do better in terms of space. 

The current implementation folds the base field value to the complex field and gets a complex poly of degree n/2.
If we do the compression logic, I think we will have a base value poly of degree n  and two complex coefficients. The space taken seems the same. So, our goal is to implement the compression/decompression logic to see if it can be more efficient than the current one.

@dlubarov, please let me know do we just want another option to implement DFT.

**Comment by dlubarov** [comment]
I think the limitation with the existing code is that it gives us compressed output for a single [I]FFT, but doesn't give us a way to perform a full low-degree extension (chaining two FFTs together) with compressed output. https://eprint.iacr.org/2023/824 would enable that.

**Comment by LKY-stephen** [comment]
I am still thinking about the work of this ticket. I misunderstood it as a DFT process, but it is more like an LDE method that extends the Mersenne31 poly to a Complex field.


BTW, while I am checking the code of LDE, I find something seems wrong. In `lde/native`

```rust
        let g = Domain::two_adic_generator(bits);
        let subgroup = cyclic_subgroup_known_order::<Domain>(g, 1 << bits).collect::<Vec<_>>();
        let weights = barycentric_weights(&subgroup);

        let lde_bits = bits + added_bits;
        let lde_subgroup = cyclic_subgroup_known_order::<Domain>(g, 1 << lde_bits);
``` 
If `g` is a two_adic_generator of order `2^bits,` I think `lde_subgroup` is just the original `subgroup`? shouldn't g be regenerated?

**Comment by dlubarov** [comment]
Good point, I made https://github.com/Plonky3/Plonky3/pull/170 with a fix

**Comment by dlubarov** [comment]
We've also been having second thoughts about this approach to Mersenne31 integration (doing a "MersenneFFT" with complex roots, compressing the output, etc.). @ulrich-haboeck and Shahar have been looking into a different approach for supporting Mersenne31, which is still being written up. It should lead to cheaper constraint evaluation, and might also be cleaner in some ways.

**Comment by dlubarov** [comment]
Closing this as we have a different plan for Mersenne integration; we can keep #56 to track progress with the new scheme.
