### ISSUE TITLE
FRI grinding (proof of work)

### ISSUE THREAD

**Issue by dlubarov** [Plonky3/Plonky3#200]
Grinding can boost security without adding queries. I think the idea was first documented in the [ethSTARK](https://eprint.iacr.org/2021/582) paper (though it was tribal knowledge before that).

There are some subtly different ways of integrating grinding into the protocol. This is what we settled on in Plonky2:
- In between FRI's commit and query phases, have the prover send an arbitrary message (Plonky2 called it `pow_witness`).
- Observe that message, i.e. treat it as part of the transcript for the purpose of Fiat-Shamir.
- Have the verifier sample a random challenge, using `CanSample` as usual.
- Have the verifier reject unless the challenge is sufficiently small.

I thought treating the witness and challenge as part of the transcript like that was a nice and clean approach. However, it does make it potentially harder for the prover to conduct its search efficiently. See this [prover code](https://github.com/0xPolygonZero/plonky2/blob/main/plonky2/src/fri/prover.rs#L115) from Plonky2.

There's also a question of how large the PoW witness should be. In Plonky2 it was a single field element, so there was a non-negligible chance that no valid PoW witness existed. Plonky2 had to deal with non-negligible completeness errors anyway, given the way it used cumulative product arguments over small fields. Plonky3 doesn't have any such non-negligible completeness errors built in, so to maintain that property, it might be best to use several field elements for the PoW witness, or make it configurable.

**Comment by rjeli** [comment]
Is my math right, that you would need 25 bits of grinding before it's an issue with a 31 bit field?
```
log2((1 - 2^-24)^(2^31)) = -184.665
log2((1 - 2^-25)^(2^31)) = -92.332
```

Concretely, it should be pretty quick to grind 25 bits, but most proven security arguments I've seen don't benefit from huge grinding. I guess it's worth implementing for conjectured, though

**Comment by dlubarov** [comment]
Hm good point, we typically use 16 bits of grinding, 24~25 bits might be around the upper limit of what anyone will want to use in practice. So maybe a single-element witness is sufficient.

**Comment by npwardberkeley** [comment]
It looks like we can't do the challenger-cloning in the same efficient way that plonky2 did, because we don't have any assumptions about the internals of `FriConfig::Challenger`. I think the best options are to either

- make `FriConfig::Challenger` require `DuplexChallenger`, and publicly expose DuplexChallenger's `sponge_state` and `input_buffer`, or
- add a new method (within its own trait?) for `FieldChallenger` to handle the entire process (make changes to the sponge state and reverse the whole process if necessary)

**Comment by dlubarov** [comment]
I think the second seems preferable, to preserve modularity.

We could also start with a simple clone (not worrying about the cost of cloning `Vec`s) for now. Not as optimized but it doesn't seem like a huge deal.

Or maybe something like this, to start with simple cloning while setting up an API for more optimized overrides later?

```rust
pub trait GrindingChallenger<F: PrimeField64>: FieldChallenger<F> + Clone {
    fn grind(&self, bits: usize) -> F {
        for i in 0..F::ORDER_U64 {
            let witness = F::from_canonical_u64(i);
            let mut fork = self.clone();
            fork.observe(witness);
            if fork.check_witness(bits, witness) {
                return witness;
            }
        }
        panic!("failed to find witness")
    }

    #[must_use]
    fn check_witness(&mut self, bits: usize, witness: F) -> bool {
        self.observe(witness);
        self.sample_bits(bits) == 0
    }
}
```

**Comment by npwardberkeley** [comment]
@dlubarov What's the reason for the second part of the `min_leading_zeros` definition here? https://github.com/0xPolygonZero/plonky2/blob/e576b3c393f71ecafd1c8c1c2f8185a225b8d494/plonky2/src/fri/prover.rs#L119 In the Plonky3 version it doesn't work because our field is 31 bits, but it's still defined as a `PrimeField64` so I can't just replace 64 with 32 I think

**Comment by dlubarov** [comment]
I think the reasoning was that we were storing the PoW response element as a canonical u64, which might introduce some "guaranteed" padding zeros. Like say if our field size was approximately 2^60, then `pow_response.to_canonical_u64()` would be guaranteed 4 zeros from padding, so we'd demand a total of `config.proof_of_work_bits + 4` zeros to get the desired probability.

**Comment by dlubarov** [comment]
I think applying that logic with either `PrimeField32` or `PrimeField64` would be fine as long as we're consistent, like if we used `PrimeField32` we'd expect `32 - field_bits` extra zeros rather than `64 - field_bits`. Probably better to use `PrimeField64` for Goldilocks compatibility though.

**Comment by npwardberkeley** [comment]
Ohhh I see. I think here we don't actually need it though? Because `sample_bits` takes the field size into account, so we're counting "leading zeros" from the size of the field element, not from a u64?

**Comment by dlubarov** [comment]
Oh right, that makes sense 👍

**Comment by dlubarov** [comment]
Done by @npwardberkeley in #205
