### ISSUE TITLE
Allow building without rayon

### ISSUE THREAD

**Issue by rjeli** [Plonky3/Plonky3#201]
Currently `p3-maybe-rayon` has parallel enabled by default, it should probably not be default, and all consumer crates need feature flags

As well, `p3-matrix`, `p3-dft`, `p3-maybe-rayon`, `p3-uni-stark`, & others need fixes to import the right traits to work seamlessly

**Comment by dlubarov** [comment]
This was done in https://github.com/Plonky3/Plonky3/pull/217
