### ISSUE TITLE
Do we need nightly for CI?

### ISSUE THREAD

**Issue by rjeli** [Plonky3/Plonky3#212]
CI uses a specific nightly from a few months ago, which can be slightly annoying when `fmt` or `clippy` behaves differently than a local stable toolchain. AFAICT everything works fine on stable. OK to change CI to stable?

**Comment by dlubarov** [comment]
I think the one thing that isn't working with stable is our rustfmt config. `cargo +stable fmt` shows

```
Warning: can't set `imports_granularity = Module`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
```

We could potentially remove the `group_imports` and `imports_granularity` options until they stabilize. I think it's nice to enforce a standardized import layout, but not a huge deal.

cc @matthiasgoergens who added the config, do you have thoughts on this?

**Comment by rjeli** [comment]
Oh I missed that thx. I agree grouped imports are nice. What about running tests & clippy on stable, and just fmt on nightly? Then we have 99% editor/lsp/ide/cli integration, and just have to run `cargo +nightly-2024-xx-yy fmt` to fix up imports before push

**Comment by matthiasgoergens** [comment]
Whatever works for you is good.

For our own project, we need nightly, and update it about twice a month.

But if stable works for you now, that's probably much easier to develop against!

(I would still try to update to the latest stable somewhat regularly.)

**Comment by dlubarov** [comment]
Relatedly, @nbgl may soon be adding code which uses nightly-only intrinsics, but plans to add some compile-time guard (details TBD) to stable builds should still be possible
