### ISSUE TITLE
Multi batch opening with different max heights in FRI

### ISSUE THREAD

**Issue by tamirhemo** [Plonky3/Plonky3#250]
When attempting to make a `open_multi_batches` call with batches that have different maximum heights, the code panics for accessing invalid rows. 

Here is an example of a test failure:
https://github.com/Plonky3/Plonky3/blob/multi-batch-fail/fri/tests/pcs.rs#L108

In the context of FRI, the problem seems to be that the shifts of degrees on the tree assume the `log_max_degree` is the same for all batches in https://github.com/Plonky3/Plonky3/blob/main/fri/src/two_adic_pcs.rs#L299:
```rust
        let query_openings = query_indices
            .into_iter()
            .map(|index| {
                prover_data_and_points
                    .iter()
                    .map(|(data, _)| {
                        let (opened_values, opening_proof) = self.mmcs.open_batch(index, data);
                        BatchOpening {
                            opened_values,
                            opening_proof,
                        }
                    })
                    .collect()
            })
            .collect();
```
That is because `query_indices` are computed with the maximum height of all batches as basis, whereas the shifts in `open_batch`, which are computed by the following code:
```rust
        let openings = prover_data
            .leaves
            .iter()
            .map(|matrix| {
                let log2_height = log2_ceil_usize(matrix.height());
                let bits_reduced = log_max_height - log2_height;
                let reduced_index = index >> bits_reduced;
                matrix.row(reduced_index).collect()
            })
            .collect_vec();
 ```
are computing the shift with respect to the maximum height of that batch. This ends up with overflow in the rows if the `max_height_for batch < max_height_on_all_batches`.

I have also checked an earlier commit of FRI, and had the same failure, so this behavior did not originate from recent fixes. 

Is this the intended behavior of `open_multi_batches`? If so, we should probably add some comments in the trait as the errors were a little confusing to debug. If it's not the intended behavior, happy to explore a fix (some naive fixes I tried didn't work).

**Comment by dlubarov** [comment]
I see a few options for addressing this:
1. Replace `Mmcs::open_batch` with a method called `open_multi_batches`, which takes multiple `ProverData`s and handles openings for all of them in a single call, similar to `UnivariatePcs::open_multi_batches`.
2. Change `Mmcs::open_batch` to take a `log_max_height` param, representing the max height of any matrix.
3. Leave `Mmcs` unchanged, and instead change `TwoAdicFriPcs` to determine the "global max height" and shift off certain bits when it calls `Mmcs::open_batch`.

I think I'm leaning toward (1) - it would make `Mmcs` more complicated, but the extra layer of batching already exists in PCS APIs, and it seems natural for `Mmcs` to have the same batching approach. That said, I'll need to try coding and see how clean/simple (or not) the changes turn out before I can confidently recommend anything.

**Comment by tamirhemo** [comment]
(1) does sound really nice, I can try to implement it too and see if it works

**Comment by dlubarov** [comment]
@tamirhemo that would be great, I'll tentatively reassign to you, but let me know if I (and/or @rjeli) can help

**Comment by hadasz** [comment]
WIP pull request: https://github.com/Plonky3/Plonky3/pull/277

**Comment by dlubarov** [comment]
I made progress on (1) but it was starting to feel like too much extra logic without a great reason for it. (3) is a very easy change, see #286, and seems like a reasonable solution I think?

**Comment by tamirhemo** [comment]
That's great, thank you! 

I think I ran into some issues with (1) as well since it seems like the logic of open_multi_batches makes less sense for the MMCS given how it's used in Pcs.
