### ISSUE TITLE
DuplexChallenger update the capicity of the sponge_state  when observe() 

### ISSUE THREAD

**Issue by cyl19970726** [Plonky3/Plonky3#365]
It seems that the code [here](https://github.com/Plonky3/Plonky3/blob/main/challenger/src/duplex_challenger.rs#L72) leads to the whole sponge_state updated by [duplex()](https://github.com/Plonky3/Plonky3/blob/main/challenger/src/duplex_challenger.rs#L42) function .

For detail,  the below code updates the whole sponge_state whose capacity partion should no be touched  
```
if self.input_buffer.len() == WIDTH {
            self.duplexing();
        }
```
<img width="661" alt="截屏2024-05-14 16 42 14" src="https://github.com/Plonky3/Plonky3/assets/52317293/176308c4-0d53-4f8f-840b-d49c68dedeb6">

```
impl<F, P, const WIDTH: usize> DuplexChallenger<F, P, WIDTH>
where
    F: Copy,
    P: CryptographicPermutation<[F; WIDTH]>,
{
    pub fn new(permutation: P) -> Self
    where
        F: Default,
    {
        Self {
            sponge_state: [F::default(); WIDTH],
            input_buffer: vec![],
            output_buffer: vec![],
            permutation,
        }
    }

    fn duplexing(&mut self) {
        assert!(self.input_buffer.len() <= WIDTH);

        // Overwrite the first r elements with the inputs.
        for (i, val) in self.input_buffer.drain(..).enumerate() {
            self.sponge_state[i] = val;
        }

        // Apply the permutation.
        self.permutation.permute_mut(&mut self.sponge_state);

        self.output_buffer.clear();
        self.output_buffer.extend(self.sponge_state);
    }
}

impl<F, P, const WIDTH: usize> FieldChallenger<F> for DuplexChallenger<F, P, WIDTH>
where
    F: PrimeField64,
    P: CryptographicPermutation<[F; WIDTH]>,
{
}

impl<F, P, const WIDTH: usize> CanObserve<F> for DuplexChallenger<F, P, WIDTH>
where
    F: Copy,
    P: CryptographicPermutation<[F; WIDTH]>,
{
    fn observe(&mut self, value: F) {
        // Any buffered output is now invalid.
        self.output_buffer.clear();

        self.input_buffer.push(value);

        if self.input_buffer.len() == WIDTH {
            self.duplexing();
        }
    }
}
```

**Comment by dlubarov** [comment]
Hm I think the permutation should apply to the entire duplex state including capacity, no? The diagram [here](https://keccak.team/sponge_duplex.html) depicts it like that -

![image](https://keccak.team/images/Duplex-150.png)

**Comment by dlubarov** [comment]
I think I misinterpreted what you said earlier, you mean the overwriting with new inputs is being applied even to capacity elements? That does seem problematic! Thanks for flagging this.

**Comment by cyl19970726** [comment]
> I think I misinterpreted what you said earlier, you mean the overwriting with new inputs is being applied even to capacity elements? That does seem problematic! Thanks for flagging this.

yes, the below picture shows a correct transformation for sponge_state(composes with 8-arity and 8-capacity given by the [fri-test](https://github.com/Plonky3/Plonky3/blob/main/fri/tests/fri.rs#L30)) over a fri case with two folding phase and 3-times query

![image](https://github.com/Plonky3/Plonky3/assets/52317293/0c78b8dd-744a-47e7-a2d3-597768e1c934)
