### ISSUE TITLE
Column rotate support

### ISSUE THREAD

**Issue by nyunyunyunyu** [Plonky3/Plonky3#371]
Here we can specify a linear combination of some columns:
https://github.com/Plonky3/Plonky3/blob/e7f55686daffa76dcd1ed2007c12af85669b4767/air/src/virtual_column.rs#L7-L19

I'm wondering if it's possible to support column rotation e.g. column A on row `X` + column B on row `X+1`.

**Comment by dlubarov** [comment]
Hm currently `VirtualPairCol` is only for describing columns with respect to a single "local" row. We could potentially generalize it to describe multiple rows within an evaluation window, but what's the use case?

**Comment by nyunyunyunyu** [comment]
> Hm currently `VirtualPairCol` is only for describing columns with respect to a single "local" row. We could potentially generalize it to describe multiple rows within an evaluation window, but what's the use case?

Thanks for taking a look into this! I can give an example about interactions(I understand this is not in plonky3 codebase but it's common in valida/sp1):
```
pub struct Interaction<F: Field> {
    pub values: Vec<VirtualPairCol<F>>,
    pub multiplicity: VirtualPairCol<F>,
    pub kind: InteractionKind,
}
```
Let's say I want to send first n fibonacci numbers. The main trace has 3 columns:
```
selector x1 x2
```
And constraints:
`next.x1 = local.selector * local.x2 + (1-local.selector) * local.x1`
`next.x2 = local.selector * (local.x1 + local.x2) + (1-local.selector) * local.x2`
Logically I want to send
```
{
  values: next.x1,
  multiplicity: local.selector,
  kind: FIBONACCI
}
```
But it's infeasible because `VirtualPairCol` doesn't support rotate.

Of cousre there could be some workaround, for exapmle
```
{
  values: local.x1 * F::one() + local.x2 * F::one(),
  multiplicity: local.selector,
  kind: FIBONACCI
}
```
But it's not ideal since developers have to duplicate some logic in constarints.
