### ISSUE TITLE
Security of FRI configuration

### ISSUE THREAD

**Issue by dongliangCai** [Plonky3/Plonky3#380]
I have noticed that some FRI configurations in the code do not perform well for production environments requiring 128-bit security. Are your FRI configurations intended solely for testing purposes?

some parameters like: 
(log_blowup: 2, num_queries: 28, proof_of_work_bits: 8)=> Less than 36 bits of security; 
(log_blowup: 1, num_queries: 10, proof_of_work_bits: 8)=> less than 13  bits of security；         
(log_blowup: 1, num_queries: 100, proof_of_work_bits: 16)=> less than 66  bits of security； 

These results are based on the deductions from the paper "Proximity Gaps for Reed-Solomon Codes" (https://eprint.iacr.org/2020/654.pdf). Please let me know if there are any issues with this assessment.

Additionally, I would like to ask for guidance on setting these parameters to achieve 128-bit security. Would the configuration 
(log_blowup: 4, num_queries:48 , proof_of_work_bits: 32) be a suitable choice?

Thank you for your reply.

**Comment by 0xkanekiken** [comment]
Winterfell has a concise explanation and [implementation](https://github.com/facebook/winterfell/blob/acb909fde4b52823bb3026f25ea8032e6ba67e6d/air/src/proof/mod.rs#L242-L351) of proven security from @ulrich-haboeck's [paper](https://eprint.iacr.org/2022/1216).

**Comment by dongliangCai** [comment]
Thank you very much for your prompt and detailed response.  I appreciate the clarification and your assistance in addressing my concerns.  Your guidance on the FRI configurations is incredibly helpful.

Thank you again for your reply!
