### ISSUE TITLE
Poseidon over BN254 support

### ISSUE THREAD

**Issue by Voidkai** [Plonky3/Plonky3#411]
Hello,

I am looking for an implementation of the MDS matrix for the Poseidon permutation over the BN254 curve. Specifically, I am interested in benchmarking the performance of Poseidon over BN254. Does such an implementation exist, or is there an existing MDS implementation that can be used for this purpose?

Thank you!

**Comment by jonathanpwang** [comment]
there is https://github.com/HorizenLabs/poseidon2/blob/main/plain_implementations/src/poseidon2/poseidon2_instance_bn256.rs for poseidon2 and https://github.com/privacy-scaling-explorations/poseidon for poseidon. I believe poseidon1 and poseidon2 are the same for the usual parameters for bn254, but the implementation is simplified in poseidon2

**Comment by dlubarov** [comment]
Something like `IntegratedCosetMds` should work out of the box, although it's mainly designed for large matrices over small fields; I imagine naive multiplication with some hardcoded low-weight matrix could give better performance for BN254.

**Comment by Voidkai** [comment]
> there is https://github.com/HorizenLabs/poseidon2/blob/main/plain_implementations/src/poseidon2/poseidon2_instance_bn256.rs for poseidon2 and https://github.com/privacy-scaling-explorations/poseidon for poseidon. I believe poseidon1 and poseidon2 are the same for the usual parameters for bn254, but the implementation is simplified in poseidon2

Thank you for your suggestions. I have tested both implementations of Poseidon and Poseidon2 that you mentioned, and I found that, compared with Poseidon,  the performance improvement of poseidon2 is still obvious for the usual parameters (width=3, degree=5, partial round=56, full round=8). I'm not sure if my conclusion is correct.

**Comment by Voidkai** [comment]
> Something like `IntegratedCosetMds` should work out of the box, although it's mainly designed for large matrices over small fields; I imagine naive multiplication with some hardcoded low-weight matrix could give better performance for BN254.

Thank you for your reply. I was wondering why there isn't an implementation of Poseidon over BN254 in Plonky3. Are there any challenges or difficulties in implementing Poseidon over BN254 in Plonky3?

**Comment by jonathanpwang** [comment]
Are you specifically referring to Poseidon1? There is https://github.com/Plonky3/Plonky3/blob/main/bn254-fr/src/poseidon2.rs for Poseidon2

**Comment by Voidkai** [comment]
Yes, I am referring to Poseidon1, and there is no MDS matrix implementation for Bn254-fr, which can be used in Poseidon1.
