### ISSUE TITLE
mixup on Multi-FRI link in LeastAuthority audit report

### ISSUE THREAD

**Issue by huitseeker** [Plonky3/Plonky3#418]
The audit report uploaded in https://github.com/Plonky3/Plonky3/commit/eeb4e37b20127c4daa871b2bad0df30a7c7380db (and currently at https://github.com/Plonky3/Plonky3/blob/main/audits/Least%20Authority-Polygon%20Plonky3%20Audit%20Report-18%20July%202024.pdf) links to Multi-FRI, an "unpublished draft by A. Green and D. Vagner" (starting at the top of p.4 in the PDF). 

The link used in those references is https://github.com/LeastAuthority/Polygon-Multi-FRI-Protocol/blob/main/Circle_STARKs.pdf, which matches https://eprint.iacr.org/2024/278, does not have those authors, and is on a different topic. This seems to be a mixup?

Cc. @brkben who uploaded the PDF at the link's destination.

**Comment by brkben** [comment]
@huitseeker We updated the wrong paper. Thank you for pointing out the mistake.

**Comment by AaronH8613b** [comment]
The report has been updated both here and on the Least Authority website with the correct link. 

https://github.com/Plonky3/Plonky3/blob/main/audits/Least%20Authority-%20Polygon%20Plonky3%20Updated%20Final%20Audit%20Report.pdf

https://leastauthority.com/blog/audits/audit-of-plonky3/

**Comment by dlubarov** [comment]
Thanks for the report and the fix!
