### ISSUE TITLE
Parallelized FFTs

### ISSUE THREAD

**Issue by dlubarov** [Plonky3/Plonky3#51]
#50 could lead to one method, but it might not be ideal, certainly now when the number of columns is less than the number of cores. Need to experiment with other approaches.

**Comment by bhgomes** [comment]
Refer to https://github.com/Plonky3/Plonky3/blob/8465193947ac5deb7dedbf6e47244f3d46cd6e69/dft/src/radix_2_bowers.rs for reference.

**Comment by dlubarov** [comment]
This is done for now, we have a `Radix2DitParallel`. There might be better ways to parallelize, I have a few ideas to try, but don't think we need to track it.
