### ISSUE TITLE
Define ~128 bit extension fields 

### ISSUE THREAD

**Issue by dlubarov** [Plonky3/Plonky3#52]
Implement extension fields for the following: 

- [ ] #113
- [x] #60
- [x] #110

`Mersenne31`'s extension should probably be a towering extension of `Mersenne31Complex`. `Goldilocks`'s extension can be adapted from Plonky2 or winterfell.

General Extension Code from plonky2: https://github.com/mir-protocol/plonky2/tree/main/field/src/extension
Goldilocks Extension Implementation: https://github.com/mir-protocol/plonky2/blob/main/field/src/goldilocks_extensions.rs

**Comment by bhgomes** [comment]
What should be the extension degrees:
- `BabyBear`: 4 or 5
- `Mersenne31`: tower 2->2 or tower 2->3
- `Goldilocks`: 2 or 3

Why not go directly to a degree 4 or 5 extension of `Mersenne31`?

**Comment by LKY-stephen** [comment]
For Goldilocks, we can directly use the one from plonky2
```
impl Extendable<2> for GoldilocksField {
    type Extension = QuadraticExtension<Self>;

    // Verifiable in Sage with
    // `R.<x> = GF(p)[]; assert (x^2 - 7).is_irreducible()`.
    const W: Self = Self(7);

    // DTH_ROOT = W^((ORDER - 1)/2)
    const DTH_ROOT: Self = Self(18446744069414584320);

    const EXT_MULTIPLICATIVE_GROUP_GENERATOR: [Self; 2] =
        [Self(18081566051660590251), Self(16121475356294670766)];

    const EXT_POWER_OF_TWO_GENERATOR: [Self; 2] = [Self(0), Self(15659105665374529263)];
}
```
For babybear, we need an extension instance for QuinticExtension or TesseracticExtension.
In this higher degree, the frobenuis algorithm becomes explicitly faster for the inverse. if we only use this extension for the prime field (i.e., we force the base field to be the prime field,) then we can embed the frobenuis algorithm inside these particular extension field structs. 

The quintic binomial poly can be `x^5-2`, the generator is i+8
The Tesseract binomial poly can be  `x^4-11`, and the generator is also i+8

**Comment by dlubarov** [comment]
Closing in favor of #113 since only `BabyBear` remains
