### ISSUE TITLE
`Mersenne31` Extension Fields

### ISSUE THREAD

**Issue by bhgomes** [Plonky3/Plonky3#60]
> Mersenne31's extension should probably be a towering extension of Mersenne31Complex. Goldilocks's extension can be adapted from Plonky2 or winterfell.
> 
> General Extension Code from plonky2: https://github.com/mir-protocol/plonky2/tree/main/field/src/extension
> Goldilocks Extension Implementation: https://github.com/mir-protocol/plonky2/blob/main/field/src/goldilocks_extensions.rs

**Comment by LKY-stephen** [comment]
The simplest irreducible poly I have found for the Mersenne31 complex is x^2+i+2. 
This generates a field of around 123bit

**Comment by LKY-stephen** [comment]
A quick comment: The new extended field seems not an OEF. I am not sure if we want to use that field in that case because its computation can be very heavy without good properties over Frobenius automorphism. I am checking if we can use some variant of the OEF algorithm.

**Comment by Nashtare** [comment]
On the other hand, one could use $x^3 - 5i$ to have an efficient reduction (though not sure this would beat $x^2+i+2$). The deg 6 extension has cardinality 186 bits. Could come in handy if one wanted to switch to the non-conjectured (i.e. proven) soundness of FRI.

**Comment by dlubarov** [comment]
I think ideally we'd support both options, i.e. one degree-2 and one degree-3 extension of `Mersenne31Complex`, since Plonky3 likes to be unopinionated about things like target security.
