### ISSUE TITLE
Optional Trait for Two Adic Field

### ISSUE THREAD

**Issue by LKY-stephen** [Plonky3/Plonky3#90]
An extension field can be a two-adic field with a subfield with the order `2^k`.

A safe way to implement a two-adic field trait for the extension field is to mention the degree and generator at the `XXExtendable` trait of the base field, such that the developer can check the real order this subfield can have

**Comment by dlubarov** [comment]
> 1. A two-adic field.
> 2. A field with a prime base field.

I didn't quite understand, are you suggesting new traits for these? I think they can already be encoded as e.g.
1. `<F: Field, EF: ExtensionField<F> + TwoAdicField>`
2. `<F: PrimeField, EF: ExtensionField<F>>`

From the discussion in #75, maybe a Frobenius trait/method isn't need, but if we do have one I think it should ideally be more general, not limited to OEFs like in Plonky2.

**Comment by LKY-stephen** [comment]
Yes, for the two-adic field, we can use the existing trait `TwoAdicField`. For frobenuis, we may need a new trait if any algorithm used that. I added this issue to split it from the previous PR so these optional features will not block our implementation of OEF.

**Comment by LKY-stephen** [comment]
Additionally, directly implementing TwoAdicField at the generic extension field struct seems not a good idea.

For example, in Plonky2, we have `const TWO_ADICITY: usize = F::TWO_ADICITY + 1;` in quadratic exteion field. But MersenComplex31 provides a counter-example that this value can be much bigger. 

I suggest adding a new property to the `OptimallyExtendable` trait so we can compute the order and the root according to the base field.

**Comment by dlubarov** [comment]
Agreed, let's add something like

```rust
const EXT_TWO_ADICITY: usize;

fn ext_two_adic_generator(bits: usize) -> Self;
```

It could go in `BinomiallyExtendable` itself, so we'd just have all `BinomialExtensionField`s impl `TwoAdicField`, or it could go in a new supertrait (`TwoAdicBinomiallyExtendable`?) if we wanted it to be optional. WDYT?

**Comment by dlubarov** [comment]
We might want a requirement that `ext_two_adic_generator()` be consistent with the base field's `two_adic_generator()` (if any), i.e.

```rust
ext_two_adic_generator().exp_power_of_2(EXT_TWO_ADICITY - TWO_ADICITY) == two_adic_generator()
```

I think we needed this in Plonky2, but I forget why, @wborgeaud do you remember?

**Comment by wborgeaud** [comment]
> I think we needed this in Plonky2, but I forget why, @wborgeaud do you remember?

Without this requirement we would get `F::two_adic_subgroup(n) != FE::two_adic_subgroup(n)` (the subgroup is the same, but the order is different). I think this causes a bunch of issues, because then the evaluation domain for the FFT is not same when doing FFTs over the base field and the extension field.

**Comment by LKY-stephen** [comment]
>It could go in BinomiallyExtendable itself, so we'd just have all BinomialExtensionFields impl TwoAdicField, or it could go in a new supertrait (TwoAdicBinomiallyExtendable?) if we wanted it to be optional. WDYT?

The Plonky3 is not designed only for FRI, so I think an optional trait is more flexible.

For ext_two_adic_generator, we have two directions:
1. We can put all logic in the base-field trait so the base field can compute all two-adic generators and EF just using the base-field trait. This solution is straightforward and efficient but makes the base field do many computations beyond its scope. 
2. Or we can only store the generator of the biggest two-adic subgroup in the trait of the base field and let the extension field compute the generator for other subgroups. This way will be much cleaner than the previous way with the cost of performance(we need to compute the exponential of EF even though those generators are almost in the base field)

Which one do you prefer?

**Comment by dlubarov** [comment]
Just to check if I understood correctly, is it
1. each `impl TwoAdicBinomiallyExtendable<D>` would contain `ext_two_adic_generator()` with exponentiation logic
2. each `impl TwoAdicBinomiallyExtendable<D>` would contain a max order two-adic generator, and the exponentiation would go in `BinomiallyExtendable`'s impl of `TwoAdicField`?

I think both are reasonable, but one advantage of (1) is that it would let us potentially replace exponentiation with a jump table (like a match on `bits` which returns one of several hardcoded generators), if we needed to speed it up later.
