### ISSUE TITLE
Potential bugs from `*_base_slice()` on different architectures

### ISSUE THREAD

**Issue by unzvfu** [Plonky3/Plonky3#96]
[`AbstractFieldExtension::{as,from}_base_slice()`](https://github.com/Plonky3/Plonky3/blob/80ef09a4b5f3b01b5a25579b0ef56591ce1fa3bd/field/src/field.rs#L218) are not really well-defined since they expose the internal choice of representation of the extension. If we have two different machine architectures whose arithmetic for a particular field extension uses two different representations (easy to imagine with CPU vs GPU or vector vs serial), then calling `u = fe.as_base_slice()` on one machine and then `v = FE::from_base_slice(u)` on another could result in garbage in `v`.

IMHO, the guiding principle should be: Any operation that depends on the internal representation of elements of a field extension needs to be defined _inside_ the field extension code. Exposing the internal representation is asking for trouble.

Thoughts?

**Comment by dlubarov** [comment]
Hm I see how this would be a concern if `Base` was an associated type, so different (conditionally compiled) impls could declare different bases. But since it's a generic, there could be multiple impls, e.g. `StarkConfig` expects two impls -
```rust
type Challenge: ExtensionField<Self::Val> + ExtensionField<Self::Domain> + TwoAdicField;
```

With that in mind, I think the methods seem okay since the caller is specifying the encoding; there could still be ambiguity from certain call sites but I would argue that it's a caller issue.

(Aside: winterfell has a similar trait named`ExtensionOf<Base>`, maybe that name is more clear to hint that multiple impls are expected?)

**Comment by unzvfu** [comment]
Hmm, I think I might not have explained myself clearly (or perhaps I've misunderstood your response). The concern is not about the choice of `Base`, it's about a (conditionally compiled) choice of extension field model.

For example, suppose we have a base 𝔽_p with p=29 and we want to represent elements of 𝔽_{p^2} = 𝔽[X]/(f(X)). If device A implements `f = X^2 - 2` and device B implements `f = X^2 + X + 1` (could be CPU and GPU in the same box), then calling `u = fe.as_base_slice()` on A and then `v = FE::from_base_slice(u)` on B will result in the wrong value in `v`. This Sage script shows what I mean by showing how multiplication gives different answers (it "doesn't commute") with an "as/from" base slice:
```
sage: _.<x> = GF(29)[]
sage: K.<a> = GF(29^2, modulus = x^2 - 2)
sage: L.<b> = GF(29^2, modulus = x^2 + x + 1)
sage: a^2
2
sage: b^2
28*b + 28
sage: s = 23*a + 26  # random element of K
sage: t = 18*a + 14  # random element of K
sage: s * t                 # product in K
7*a + 3
sage: (23*b + 26) * (18*b + 14)   # L::from_base_slice(s.as_base_slice()) * L::from_base_slice(t.as_base_slice())
28*b + 8                   # not equal to L::from_base_slice((s*t).as_base_slice())
```
Does that make sense?

**Comment by unzvfu** [comment]
After further discussion (offline) we have decided that a full resolution of this issue can be postponed until we have some competing field extension models that make it concrete, at which point we'll address how best to handle it. In the meantime, an upcoming PR will add some comments to the affected functions to alert users of their dependence on implementation details.
